### ISSUE TITLE
support RSS1 feeds

### ISSUE THREAD

**Issue by legrostdg** [k0ral/imm#10]
Some (rare) websites still use RSS1 feeds... Would it be possible to support these in `imm`?

**Comment by k0ral** [comment]
I'll try and implement that in `rss-conduit` package, based on [this specification][1]. Then `imm` will benefit from it with minor changes.
Would you know of an actual RSS1 feed that I could use for testing purpose ?

[1]: http://web.resource.org/rss/1.0/spec

**Comment by legrostdg** [comment]
You can use http://planet.debian.org/rss10.xml

**Comment by k0ral** [comment]
Implemented in d34061c116156dabb0ec2f7fff65cbeede578ac2. Could you please validate on your side ?

**Comment by k0ral** [comment]
Integrated in release 1.2.0.0 .
