### ISSUE TITLE
add support for stack

### ISSUE THREAD

**Issue by legrostdg** [k0ral/imm#11]
`dyre` seems to fail with `stack`, but `stack run` (exists since 1.9.1) should allow to write a script which would emulate `dyre` functionnality.

`taffybar` has the same problem, see https://github.com/taffybar/taffybar/issues/158 (EDIT: corrected link to issue)

**Comment by k0ral** [comment]
The linked issue from taffybar looks unrelated, is that a mistake ?
I'm not fond of making `stack` a requirement to use `imm`.
But I'm also not fond of `dyre` dependency and I'm considering switching to a more "restrained" configuration system like dhall.

**Comment by legrostdg** [comment]
Woops! Sure the '8' got removed by mistake :). Not a found either of `stack` requirement, it's just that `dyre` impose using `cabal`. Using `dhall` would be sure be great!

**Comment by k0ral** [comment]
[Release 1.6.0.0](https://hackage.haskell.org/package/imm) does not depend on `dyre` anymore.
