### ISSUE TITLE
Httpie external dependency

### ISSUE THREAD

**Issue by tim2CF** [k0ral/imm#12]
Imm executable depends on httpie.
https://github.com/httpie/httpie
Probably this should be mentioned in readme file.

**Comment by k0ral** [comment]
*imm* used to depend on *httpie* until version 1.10, and [the README file for that version](https://github.com/k0ral/imm/blob/1.10.0.0/README.md) used to mention it.
Unless I am mistaken, *imm* shouldn't depend anymore on *httpie* in version 2.0 .
Could you please check which version of *imm* you are using ?
