### ISSUE TITLE
Please provide a proper license tag in the Cabal file

### ISSUE THREAD

**Issue by peti** [k0ral/imm#8]
Would you consider using a license type that's supported by Cabal for your package so, i.e. the `PublicDomain` license?

**Comment by k0ral** [comment]
What's the issue with `OtherLicense` ?

**Comment by peti** [comment]
It's not a license. It's a dummy entry that means "I don't know" and that does not convey any information. This makes life harder for people to try to distribute your packages, i.e. in NixOS or openSUSE because we cannot tell whether the package is free software or not from the Cabal file.

**Comment by k0ral** [comment]
On one hand, `OtherLicense` is an admission of ignorance, on the other hand `PublicDomain` is a lie given that the project is published under WTFPL which is not equivalent to public domain.
If lying is what it takes to save lives, I'll consider crossing the line :) .

**Comment by peti** [comment]
I am not a lawyer. I just saw that some people [do consider the license equivalent to "public domain"](https://en.wikipedia.org/wiki/WTFPL#Discussion). Personally, I would like best if you would re-license your project under an established free software license like BSD2 or MIT, because those licenses accomplish the same thing without ambiguity or profanity. It's your call, though, just my 2 cents. I'm seeing this issue entirely through the glasses of someone who wants to maximize the convenience for people who package and distribute your code -- and for us, established well-known licenses are great.

**Comment by k0ral** [comment]
License is now `PublicDomain` as of release 1.2.0.0 .
