### ISSUE TITLE
add filters

### ISSUE THREAD

**Issue by legrostdg** [k0ral/imm#9]
It would be great to be able to use some kind of "filter". A filter would be configurable for each feed, and it would turn a specific webpage to a rss/atom feed, which would then be processed by imm internals.

I may help if the feeds were specified in the configuration file (and not the db), to be able to add haskell filters.

**Comment by k0ral** [comment]
I guess it's not too much effort to add an intermediate conduit between the input HTML and the RSS/Atom parser, as a placeholder for your filter. I'll have a look and come back to you.

**Comment by legrostdg** [comment]
Great!

I don't get how you could apply a specific filter to a specific feed, if you have the feeds specified in the db. Do you have an idea in mind?

**Comment by k0ral** [comment]
The behavior can be customized through the DSL/interpreter pattern (cf [this module][1] for more information). I can see at least 2 solutions:
- the intermediate conduit can be put in the HTTP interpreter, such that the feed URI can be used to choose a filter: `filter :: URI -> Conduit Event m Event`
- the intermediate conduit can be a new standalone interpreter, with access to the `DatabaseEntry` to choose a filter (which includes URI and even a category name): `filter :: DatabaseEntry -> Conduit Event m Event`

[1]: https://hackage.haskell.org/package/imm-1.1.0.0/docs/Imm-Boot.html

**Comment by legrostdg** [comment]
OK, I did not think about these two possibilities. Maybe the first one would be easier? It would be great to have some kind of helpers.

**Comment by k0ral** [comment]
Actually, after second though, I'm creating a new XML parser interpreter, where your filter will fit nicely.

**Comment by k0ral** [comment]
Implemented in dcc7021ea2d136d6149c8383027a34f2bfa9c1a4. Could you please check out master branch and validate that it meets your requirements, before I make an official release out of it ?

**Comment by legrostdg** [comment]
Could you update the example in `Imm.Boot` to use `coXmlParser`? It would help there was some logic to select some different filters based on the uri.

**Comment by legrostdg** [comment]
It seems great! Thanks a lot, I guess I'll obsolete [perfeed](https://gitweb.gueux.org/?p=perfeed.git;a=summary) and use `imm` soon :-).

**Comment by k0ral** [comment]
Updated example in `Imm.Boot`.

**Comment by k0ral** [comment]
Integrated in release 1.2.0.0 .
